apiVersion: apps/v1
kind: Deployment
metadata:
  name: mani-nginx
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mani-nginx
  template:
    metadata:
      labels:
        app: mani-nginx
    spec:
      containers:
      - name: mani-nginx
        image: asia-south1-docker.pkg.dev/devops-learning-501612/dev-docker-repo/mani-nginx:v1
        ports:
        - containerPort: 80
